lib/messenger_web/router.ex
defmodule MessengerWeb.Router do
  use MessengerWeb, :router

  import MessengerWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {MessengerWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
    plug MessengerWeb.Plugs.Locale, "en"
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", MessengerWeb do
    pipe_through :browser


    get "/home/:username", MessengerController, :profile

    resources "/products", ProductController
  end

  # Other scopes may use custom stacks.
  # scope "/api", MessengerWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: MessengerWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  ## Authentication routes

  scope "/", MessengerWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/", PageController, :index
    post "/users/register", UserRegistrationController, :create

    get "signin", PageController, :signin
    post "/users/log_in", UserSessionController, :create

    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", MessengerWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/home", MessengerController, :home

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", MessengerWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :edit
    post "/users/confirm/:token", UserConfirmationController, :update
  end
end

lib/messenger_web/templates/page/signin.html.heex
<!DOCTYPE html>
<html lang="en">

<head>
		<meta charset="utf-8">
		<title>SHUP8 – Messenger</title>
		<meta name="description" content="#">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<!-- Bootstrap core CSS -->
		<link href="/dist/css/lib/bootstrap.min.css" type="text/css" rel="stylesheet">
		<!-- Swipe core CSS -->
		<link href="/dist/css/swipe.min.css" type="text/css" rel="stylesheet">
		<!-- Favicon -->
		<link href="/dist/img/favicon.png" type="image/png" rel="icon">
	</head>
	<body class="start">
		<main>
			<div class="layout">
				<!-- Start of Sign In -->
				<div class="main order-md-1">
					<div class="start">
						<div class="container">
							<div class="col-md-12">
								<div class="content">
									<h1>Sign in to Messenger</h1>
									<div class="third-party">
										<button class="btn item bg-blue">
											<i class="material-icons">pages</i>
										</button>
										<button class="btn item bg-teal">
											<i class="material-icons">party_mode</i>
										</button>
										<button class="btn item bg-purple">
											<i class="material-icons">whatshot</i>
										</button>
									</div>
									<p>or use your email account:</p>
                                    <.form let={f} for={@conn} action={Routes.user_session_path(@conn, :create)} as={:user}>
                                        <%= if @error_message do %>
                                            <div class="alert alert-danger">
                                            <p><%= @error_message %></p>
                                            </div>
                                        <% end %>

                                        <div class="form-group">
                                            <%= email_input f, :email, id: "inputEmail", placeholder: "Email Address",  class: "form-control", required: true %>
											<button class="btn icon"><i class="material-icons">mail_outline</i></button>
										</div>

                                        <div class="form-group">
                                            <%= password_input f, :password, id: "inputPassword", placeholder: "Password",  class: "form-control", required: true %>
											<button class="btn icon"><i class="material-icons">lock_outline</i></button>
										</div>

                                        <%= label f, :remember_me, "Keep me logged in for 60 days" %>
                                        <%= checkbox f, :remember_me %>

                                        <%= submit "Log in", class: "btn button" %>
                                    </.form>

                                    <p>
                                        
                                        <%= link "Forgot your password?", to: Routes.user_reset_password_path(@conn, :new) %>
                                    </p>
									
								</div>
							</div>
						</div>
					</div>
				</div>
				<!-- End of Sign In -->
				<!-- Start of Sidebar -->
				<div class="aside order-md-2">
					<div class="container">
						<div class="col-md-12">
							<div class="preference">
								<h2>Hello, Shupper!</h2>
								<p>Enter your personal details and start your journey with SHUP8 Messenger today.</p>
                                <%= link "Sign Up", class: "btn button", to: Routes.page_path(@conn, :index) %>
							</div>
						</div>
					</div>
				</div>
				<!-- End of Sidebar -->
			</div> <!-- Layout -->
		</main>
		<!-- Bootstrap core JavaScript
		================================================== -->
		<!-- Placed at the end of the document so the pages load faster -->
		<script src="/dist/js/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
		<script>window.jQuery || document.write('<script src="dist/js/vendor/jquery-slim.min.js"><\/script>')</script>
		<script src="/dist/js/vendor/popper.min.js"></script>
		<script src="/dist/js/bootstrap.min.js"></script>
	</body>

</html>

lib/messenger_web/templates/page/signup.html.heex
<!DOCTYPE html>
<html lang="en">

<head>
		<meta charset="utf-8">
		<title>SHUP8 – Messenger</title>
		<meta name="description" content="#">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<!-- Bootstrap core CSS -->
		<link href="/dist/css/lib/bootstrap.min.css" type="text/css" rel="stylesheet">
		<!-- Swipe core CSS -->
		<link href="/dist/css/swipe.min.css" type="text/css" rel="stylesheet">
		<!-- Favicon -->
		<link href="/dist/img/favicon.png" type="image/png" rel="icon">
	</head>
	<body class="start">
		<main>
			<div class="layout">
				<!-- Start of Sign Up -->
				<div class="main order-md-2">
					<div class="start">
						<div class="container">
							<div class="col-md-12">
								<div class="content">
									<h1>Get Started</h1>
									<div class="third-party">
										<button class="btn item bg-blue">
											<i class="material-icons">pages</i>
										</button>
										<button class="btn item bg-teal">
											<i class="material-icons">party_mode</i>
										</button>
										<button class="btn item bg-purple">
											<i class="material-icons">whatshot</i>
										</button>
									</div>
									<p>or use your email for registration:</p>
									<.form let={f} for={@changeset} class="signup" action={Routes.user_registration_path(@conn, :create)}>
									  	<%= if @changeset.action do %>
											<div class="alert alert-danger">
												<p>Oops, something went wrong! Please check the errors below.</p>
											</div>
										<% end %>
										<div class="form-parent">
											<div class="form-group">
												<%= text_input f, :firstname, id: "inputName", class: "form-control", placeholder: "First Name", required: true %>
												<button class="btn icon"><i class="material-icons">person_outline</i></button>
												<%= error_tag f, :firstname %>
											</div>
											<div class="form-group">
												<%= text_input f, :lastname, id: "inputName", class: "form-control", placeholder: "Last Name", required: true %>
												<button class="btn icon"><i class="material-icons">person_outline</i></button>
												<%= error_tag f, :lastname %>
											</div>
										</div>
										<div class="form-parent">
											<div class="form-group">
												<%= text_input f, :username, id: "inputName", class: "form-control", placeholder: "Username", required: true %>
												<button class="btn icon"><i class="material-icons">account_box</i></button>
												<%= error_tag f, :username %>
											</div>
											<div class="form-group">
												<%= email_input f, :email, id: "inputEmail", class: "form-control", placeholder: "Email Address", required: true %>
												<button class="btn icon"><i class="material-icons">mail_outline</i></button>
												<%= error_tag f, :email %>
											</div>
										</div>
										<div class="form-group">
											<%= text_input f, :image_url, id: "inputName", class: "form-control", placeholder: "Image URL", required: true %>
											<button class="btn icon"><i class="material-icons">image</i></button>
											<%= error_tag f, :image_url %>
										</div>
										<div class="form-group">
											<%= password_input f, :password, id: "inputPassword", class: "form-control", placeholder: "Password", required: true %>
											<button class="btn icon"><i class="material-icons">lock_outline</i></button>
											<%= error_tag f, :password %>
										</div>
										<div>
											<%= submit "Create Account", class: "btn button"%>
										</div>
										<div>
											<%= link "Forgot your password?", to: Routes.user_reset_password_path(@conn, :new) %>
										</div>
									</.form>
								</div>
							</div>
						</div>
					</div>
				</div>
				<!-- End of Sign Up -->
				<!-- Start of Sidebar -->
				<div class="aside order-md-1">
					<div class="container">
						<div class="col-md-12">
							<div class="preference">
								<h2>Welcome Back!</h2>
								<p>To keep connected with your friends please login with your personal info.</p>
								<%= link "Sign in", class: "btn button", to: Routes.page_path(@conn, :signin) %>
							</div>
						</div>
					</div>
				</div>
				<!-- End of Sidebar -->
			</div> <!-- Layout -->
		</main>
		<!-- Bootstrap core JavaScript
		================================================== -->
		<!-- Placed at the end of the document so the pages load faster -->
		<script src="/dist/js/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
		<script>window.jQuery || document.write('<script src="/dist/js/vendor/jquery-slim.min.js"><\/script>')</script>
		<script src="/dist/js/vendor/popper.min.js"></script>
		<script src="/dist/js/bootstrap.min.js"></script>
	</body>
</html>